# config/app_config.yaml
firebase:
  credentials_path: "config/firebase_cred.json"

collection:
  regions:
    - name: "Europe-Mediterranean"
      south: 35.0
      north: 45.0
      west: -5.0
      east: 35.0
    # Add more regions as needed

processing:
  batch_size: 500
  rate_limit: 60